[INFO     2010-11-30 20:39:40,579 bulkloader.py] Logging to bulkloader-log-20101130.203940
[INFO     2010-11-30 20:39:40,579 bulkloader.py] Throttling transfers:
[INFO     2010-11-30 20:39:40,579 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2010-11-30 20:39:40,579 bulkloader.py] HTTP connections: 8/second
[INFO     2010-11-30 20:39:40,579 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2010-11-30 20:39:40,579 bulkloader.py] Batch Size: 5
[INFO     2010-11-30 20:39:40,595 bulkloader.py] Opening database: bulkloader-progress-20101130.203940.sql3
[DEBUG    2010-11-30 20:39:41,040 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2010-11-30 20:39:41,041 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = localhost:8080
[DEBUG    2010-11-30 20:39:42,191 bulkloader.py] Bulkloader using app_id: mol-apps
[INFO     2010-11-30 20:39:42,191 bulkloader.py] Connecting to localhost:8080/remote_api
[DEBUG    2010-11-30 20:39:42,225 bulkloader.py] [Thread-2] ProgressTrackerThread: started
[DEBUG    2010-11-30 20:39:42,225 bulkloader.py] [Thread-3] DataSourceThread: started
[INFO     2010-11-30 20:39:42,225 bulkloader.py] Starting import; maximum 5 entities per post
[DEBUG    2010-11-30 20:39:42,227 bulkloader.py] [Thread-3] DataSourceThread: exiting
[DEBUG    2010-11-30 20:39:42,228 bulkloader.py] Waiting for worker threads to finish...
[DEBUG    2010-11-30 20:39:42,255 adaptive_thread_pool.py] [WorkerThread-0] Got work item [1-4]
[ERROR    2010-11-30 20:39:42,270 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread:
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1275, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 417, in create_entity
    entity = self.dict_to_entity(input_dict, self.bulkload_state)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 133, in dict_to_entity
    self.__run_import_transforms(input_dict, instance, bulkload_state_copy)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 232, in __run_import_transforms
    value = self.__dict_to_prop(transform, input_dict, bulkload_state)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 188, in __dict_to_prop
    value = transform.import_transform(value)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_parser.py", line 93, in __call__
    return self.method(*args, **kwargs)
  File "/home/andrew/code/workspace/MOL/tileapp/util.py", line 19, in wrapper
    out += bEncode(int(tmp,2))
UnboundLocalError: local variable 'out' referenced before assignment
[DEBUG    2010-11-30 20:39:42,271 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: exiting
[INFO     2010-11-30 20:39:42,729 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2010-11-30 20:39:42,730 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2010-11-30 20:39:42,730 adaptive_thread_pool.py] Error in WorkerThread-0: local variable 'out' referenced before assignment
[DEBUG    2010-11-30 20:39:42,731 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 150, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 846, in _TransferItem
    self.content = self.request_manager.EncodeContent(self.rows)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1275, in EncodeContent
    entity = loader.create_entity(values, key_name=key, parent=parent)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 417, in create_entity
    entity = self.dict_to_entity(input_dict, self.bulkload_state)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 133, in dict_to_entity
    self.__run_import_transforms(input_dict, instance, bulkload_state_copy)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 232, in __run_import_transforms
    value = self.__dict_to_prop(transform, input_dict, bulkload_state)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 188, in __dict_to_prop
    value = transform.import_transform(value)
  File "/home/andrew/code/google_appengine/google/appengine/ext/bulkload/bulkloader_parser.py", line 93, in __call__
    return self.method(*args, **kwargs)
  File "/home/andrew/code/workspace/MOL/tileapp/util.py", line 19, in wrapper
    out += bEncode(int(tmp,2))
UnboundLocalError: local variable 'out' referenced before assignment

[DEBUG    2010-11-30 20:39:42,732 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2010-11-30 20:39:42,829 bulkloader.py] [Thread-2] ProgressTrackerThread: exiting
[DEBUG    2010-11-30 20:39:42,846 bulkloader.py] ... done.
[INFO     2010-11-30 20:39:42,847 bulkloader.py] 4 entites total, 0 previously transferred
[INFO     2010-11-30 20:39:42,847 bulkloader.py] 0 entities (257 bytes) transferred in 2.3 seconds
[INFO     2010-11-30 20:39:42,847 bulkloader.py] Some entities not successfully transferred
